"""make activities team_id nullable

Revision ID: d8a95031cd1f
Revises: 
Create Date: 2026-03-18 20:06:33.537553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a95031cd1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_activities_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key('fk_activities_users', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_activities_groups', 'groups', ['group_id'], ['id'])

    with op.batch_alter_table('task_completion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_completion_requests_batch_id'), ['batch_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_tasks', 'tasks', ['parent_task_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_activity_id'), ['activity_id'], unique=False)
        batch_op.create_foreign_key('fk_teams_activities', 'activities', ['activity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teams_activities', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_teams_activity_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_tasks', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_parent_task_id'))

    with op.batch_alter_table('task_completion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_completion_requests_batch_id'))

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_groups', type_='foreignkey')
        batch_op.drop_constraint('fk_activities_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activities_group_id'))
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
